import './styles/globals.css';
import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "Meu Aniversario",
  description: "Generated by Elsa Chimba",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt">
       <link
          href="https://fonts.googleapis.com/css2?family=Lobster&display=swap"
          rel="stylesheet"
        />
      <body>
        {children}
      </body>
    </html>
  );
}
